{% set name = "esi-utils-cartopy" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://code.usgs.gov/ghsc/esi/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4e9ee616b183308a4bbb4a4fc06b2cbd7f6edc34bd2ec664165babdb88cec384

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - cartopy
    - matplotlib-base
    - numpy
    - pyproj
    - esi-utils-geo >=0.9.0

test:
  imports:
    - esi_utils_cartopy
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://code.usgs.gov/ghsc/esi/esi-utils-cartopy
  summary: 'Cartopy-dependent utilities for USGS Earthquake real time products'
  description: |
    Cartopy-dependent utilities for USGS Earthquake real time products.
  license: LicenseRef-Public-Domain
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
